{
 "title": "Perfstat Issues",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "query": "danger_score" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Danger",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(danger_score{group=\"\",type=\"\",host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Bottlenecks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(danger_score{group!=\"\",type=\"bottleneck\",host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Risk Score",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(danger_score{group!=\"\",type=\"risk\",host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Danger types",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "danger_score{group!=\"\",type!=\"\",host=~\"$host\"}>0"
    }
   ]
  },
  {
   "title": "Hosts danger",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "danger_score{type=\"\",group=\"\",host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "$host - Issues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "issue_score{host=~\"$host\"}>0",
     "legendFormat": "{{host}} {{id}} {{resource_name}} {{related_resource_name}}"
    }
   ]
  },
  {
   "title": "$host - Resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "issue_resource_value{host=~\"$host\"}>0",
     "legendFormat": "{{host}} {{id}} {{resource_name}} {{related_resource_name}}"
    }
   ]
  }
 ]
}